// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvlablnynrzadgsfbdof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2bGFibG55bnJ6YWRnc2ZiZG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNjk2OTAsImV4cCI6MjA1ODg0NTY5MH0.tvfwkQuUWGEqmLY89HZgq4jQoKQ_ENMWxxXEFfjrXeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);